config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"
  devise_for :users
  get 'tweets/index'
  
  # get 'about', to: 'static_pages#about'
  
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
     get :following, :followers
    end
    collection do
      get 'about'
    end
    collection do
      get 'kiyaku'
    end
    collection do
      get 'privacy'
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
    collection do
      get 'search'
    end
    collection do
      get 'about'
    end
    collection do
      get 'kiyaku'
    end
    collection do
      get 'privacy'
    end
  end
    
  # get '/tweet/hashtag/:name', to: "tweets#hashtag"
  
  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # belongs_to :user
  # has_many :tweets
  validates :image,:text,:sex,:tall,:title,:temp, presence: true 
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  

  def self.search(search)
    if search
      Tweet.where('text LIKE(?) or title LIKE(?)  or sex LIKE(?)  or typestyle LIKE(?)',"%#{search}%", "%#{search}%", "%#{search}%","%#{search}%")
    else
      Tweet.all
    end
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    @tweets = Tweet.all.order(created_at: :desc).page(params[:page]).per(20)
    @tweet=Tweet.new
    @all_ranks = Tweet.find(Like.group(:tweet_id).order('count(tweet_id) desc').limit(4).pluck(:tweet_id))
  end
  def new
    @tweet = Tweet.new
  end
  def create
    @tweet = Tweet.create(tweet_params)
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end
  def edit
    @tweet = Tweet.find(params[:id]) 
  end
  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
  end
 
  def show
    @tweet = Tweet.find(params[:id]) 
    @like = Like.new
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end
  
  def search
    @tweets = Tweet.search(params[:keyword]).order(created_at: :desc).page(params[:page]).per(20)
    @tweet=Tweet.new
    @all_ranks = Tweet.find(Like.group(:tweet_id).order('count(tweet_id) desc').limit(3).pluck(:tweet_id))
  end
  

  private
  def tweet_params
    params.require(:tweet).permit(:name,:image,:title,:text,:sex,:tall,:temp,:typestyle).merge(user_id: current_user.id)
  end

  
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_footer.html.haml
.footer
  .footer_p
    %ul.footer_p_link
      %li.p-footer_link_list
        = link_to about_tweets_path do
          KStagramとは
      %li.p-footer_link_list
        = link_to kiyaku_tweets_path do
          利用規約
      %li.p-footer_link_list
        = link_to privacy_tweets_path do
          プライバシーポリシー
      %li.p-footer_link_list
        = link_to destroy_user_session_path, method: :delete do
          ログアウト
  .footersite Copyright © KStagram 2020

app/views/tweets/_header.html.haml
.header_bar
  %h1.header_bar_1
  %a{ href: '/',class: 'header_main' }
    KStagram
  %ul.user_info
    .search
      = form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form|
        = form.text_field :keyword, placeholder: " 検索...", class: "search-input"
        -# = form.submit  class: "search-btn"
        %button.search-btn{:type => "submit"}
          %i.fas.fa-search
          
        
       
      

    %li.user_info_home
    = link_to root_path do
      %i.fas.fa-home
    %li.user_info_insta
    = link_to new_tweet_path do
      %i.fab.fa-instagram
    %li.user_info_heart
    = link_to root_path do
      %i.fas.fa-heart
    %li.user_info_insta
    = link_to asset_url("/users/#{current_user.id}") do
      %i.fa.fa-user
    

app/views/tweets/_main.html.haml
.mainsmainss
.main_main
  .main_main_left
    .main_main_left_tops 
      %h2.main_main_left_tops_time 
        現在の時刻
      .lefttop
        =Time.current.strftime("%Y-%m-%d %H:%M")
    .leftcontents
      .leftcontents_top
        %h2.leftcontents_top_rankname 
          %li.fas.fa-street-view ランキング
        .user_rank 
          - @all_ranks.length >= 0
          - @all_ranks.each.with_index(1) do |tweet, i|
            .user_rank_ranks
              第
              = i
              位
            .user_rank_show
              .user_rank_show_image
                %p.user_rank_show_image_names
                  =image_tag(tweet.user.image_url)
              .user_rank_show_name
                %a{:href => "/users/#{tweet.user.id}"}= tweet.user.name
                
          
        
        -# %ul.p-rankinglist a
       
    .leftbottom
      .leftbottom_down 
        %h2.tagname 
          %li.fas.fa-tags オススメタグ
          

  .main
    .main_index
      - @tweets.each do |tweet|
        .content{:style => "background-image: url(#{tweet.image});"}
          = link_to asset_url("/tweets/#{tweet.id}", method: :get) do
            = image_tag "/tweets/#{tweet.id}", method: :get

          .mainname
            .mainname_left
              =tweet.user.name
            .mainname_right
              = tweet.updated_at.strftime("%Y-%m-%d %H:%M")
    = paginate(@tweets)

  

app/views/tweets/a.html.haml
%img{:src => "/user_images/#{@user.image_name}"}/

app/views/tweets/about.html.haml
.wrapper
  = render "header"
  .mainsmainss
  .about
    .about_name
      %h2.nametitle KStgramとは・・・
      .about_name_shousai
        %p ファッションコーディネートアプリです
      .about_name_shousai1
        %p 普段着る服、気温によって着る服装をピックアップして記録・共有できるサービスです。
      -# .aboutslide
      -#   %ul.aboutslide-list
      -#     %li.slide.active
      -#       %h2 トップ画面
      -#       .a1
      -#     %li.slide
      -#       .a2
      -#     %li.slide
      -#       %img{:src => "https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/jquery/advanced/autumn.jpg"}/
      -#     %li.slide
      -#       %img{:src => "https://s3-ap-northeast-1.amazonaws.com/progate/shared/images/lesson/jquery/advanced/winter.jpg"}/
        -# .aboutbtn
        -#   .aboutbtn_math 1
        -#   .aboutbtn_math 2
        -#   .aboutbtn_math 3
        -#   .aboutbtn_math 4
          
      %section
        .aboutmenu
          .aboutmenu_all
            .aboutmenu_all-left
              .aboutmenu_all-left-icon 
                .abouticonda
                  %i.fas.fa-home
                .aboutmenuran-title  ホームボタン
            .aboutmenu_all-right トップページに戻ります
        .aboutmenu  
          .aboutmenu_all
            .aboutmenu_all-left
              .aboutmenu_all-left-icon 
                .abouticonda
                  %i.fab.fa-instagram
                .aboutmenuran-title  新規登録
            .aboutmenu_all-right 投稿ページに遷移します
        .aboutmenu  
          .aboutmenu_all
            .aboutmenu_all-left
              .aboutmenu_all-left-icon 
                .abouticonda
                  %i.fas.fa-heart
                .aboutmenuran-title  プロフィール画面
            .aboutmenu_all-right 投稿ページに遷移します
        .aboutmenu  
          .aboutmenu_all
            .aboutmenu_all-left
              .aboutmenu_all-left-icon 
                .abouticonda
                  %i.fa.fa-user
                .aboutmenuran-title  ログアウト
            .aboutmenu_all-right ログアウトします
        .aboutmenu  
          .aboutmenu_all
            .aboutmenu_all-left
              .aboutmenu_all-left-icon 
                .abouticonda
                  %i.fas.fa-search
                .aboutmenuran-title  検索
            .aboutmenu_all-right 投稿情報を検索します   
  =render "footer"

app/views/tweets/create.html.haml
.newreg
  .contents.row
    .success
      %h3.1ksk
        投稿が完了しました。
      %a.btn{:href => "/tweets"} 投稿一覧へ戻る

app/views/tweets/destroy.html.haml
.newreg
  .contents.row
    .success
      %h3.1ksk
        削除が完了しました。
      %a.btn{:href => "/tweets"} 投稿一覧へ戻る

app/views/tweets/edit.html.haml
.wrappers
  = render "header" 
  .gbl_main
    .gbl_main_title
      .gbl_main_title_container
        .gbl_main_title_container_titles
          %h1.tit.icon_font
            %span.ico
            %i.fab.fa-instagram
            %i.stst コーディネート投稿編集
  .gbl
    .gbl_body
      .gbl_body_contena 
        %h3.btnaa
          ファッション画像
        = form_for @tweet do |form| 
          = form.text_field :title, placeholder: "タイトル"
          .sectionimages
            .subsubsub
              .subsubimagebox
                %span.icoico
                %span.icoimage
                  %i.fas.fa-images
            .mainmainimage
              .mainajaxmain
              %p.mainaakjs
                = form.file_field :image, class: "image_form"
                %span.textextx
                  写真アップロード
          = form.select :temp, ['選択してください','-50℃','-40℃','-30℃','-20℃','-10℃','-9℃','-8℃','-7℃','-6℃','-5℃','-4℃','-3℃','-2℃','-1℃','0℃','1℃','2℃','3℃','4℃','5℃','6℃','7℃','8℃','9℃','10℃','11℃','12℃','13℃','14℃','15℃','16℃','17℃','18℃','19℃','20℃','21℃','22℃','23℃','24℃','25℃','26℃','27℃','28℃','29℃','30℃','31℃','32℃','33℃','34℃','35℃','36℃','37℃','38℃','39℃','40℃','41℃','42℃','43℃','44℃','45℃','46℃','47℃','48℃','49℃','50℃','51℃','52℃','53℃','54℃','55℃','56℃', '57℃', '58℃','59℃','60℃','70℃','80℃','90℃','100℃']
          = form.select :typestyle, ['冷え性', '普通', '暑がり']
          = form.select :sex, ['メンズ', 'レディース', 'ユニセックス','キッズ']
          = form.select :tall,['50cm','60cm','70cm','80cm','90cm','100cm','110cm','120cm','121cm','122cm','123cm','124cm','125cm','126cm','127cm','128cm','129cm','130cm','131cm','132cm','133cm','134cm','135cm','136cm','137cm','138cm','139cm','140cm','141cm','142cm','143cm','144cm','145cm','146cm','147cm','148cm','149cm','150cm','151cm','152cm','153cm','154cm','155cm','156cm','157cm','158cm','159cm','160cm','161cm','162cm','163cm','164cm','165cm','166cm','167cm','168cm','169cm','170cm','171cm','172cm','173cm','174cm','175cm','176cm','177cm','178cm','179cm','180cm','181cm','182cm','183cm','184cm','185cm','186cm','187cm','188cm','189cm','190cm','191cm','192cm','193cm','194cm','195cm','196cm','197cm','198cm','199cm','200cm','210cm','220cm','230cm','240cm','250cm','260cm','270cm']
          = form.text_area :text, placeholder: "コーデ詳細", rows: "10"
          = form.submit "投稿する" , { :class => 'submit-btn' }
    =render "footer"

app/views/tweets/index.html.haml
.wrapper
  = render "header"
  = render "main"
  = render "footer" 
    

app/views/tweets/kiyaku.html.haml
.wrapper
  = render "header"
  .kiyaku
    .kiyaku_show
      .kiyaku_show_content
        %h1 利用規約
        %p この利用規約（以下，「本規約」といいます。）は，本サービス運営チーム（以下，「運営チーム」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
        %br
        %h2 第1条（適用）
        %ol
          %li 本規約は，ユーザーと運営チームとの間の本サービスの利用に関わる一切の関係に適用されるものとします。
          %li 運営チームは本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。
          %li 本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。
          %br
        %h2 第2条（利用登録）
        %ol
          %li 本サービスにおいては，登録希望者が本規約に同意の上，運営チームの定める方法によって利用登録を申請し，運営チームがこれを承認することによって，利用登録が完了するものとします。
          %li 運営チームは，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。
          %ol 
            %li 利用登録の申請に際して虚偽の事項を届け出た場合
            %li 本規約に違反したことがある者からの申請である場合
            %li その他，運営チームが利用登録を相当でないと判断した場合
            %br
        %h2 第3条（ユーザーIDおよびパスワードの管理）
        %ol
          %li ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。
          %li ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。運営チームは，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。
          %li ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，運営チームに故意又は重大な過失がある場合を除き，運営チームは一切の責任を負わないものとします。
          %br
        %h2 第4条（利用料金および支払方法）
        %ol
          %li ユーザーは，本サービスの有料部分の対価として，運営チームが別途定め，本ウェブサイトに表示する利用料金を，運営チームが指定する方法により支払うものとします。
          %li ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。
          %br
        %h2 第5条（禁止事項）
        %p ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。
        %ol
          %li 法令または公序良俗に違反する行為
          %li 犯罪行為に関連する行為
          %li 本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為
          %li 運営チーム，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為
          %li 本サービスによって得られた情報を商業的に利用する行為
          %li 運営チームのサービスの運営を妨害するおそれのある行為
          %li 不正アクセスをし，またはこれを試みる行為
          %li 他のユーザーに関する個人情報等を収集または蓄積する行為
          %li 不正な目的を持って本サービスを利用する行為
          %li 本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為
          %li 他のユーザーに成りすます行為
          %li 運営チームが許諾しない本サービス上での宣伝，広告，勧誘，または営業行為
          %li 面識のない異性との出会いを目的とした行為
          %li 運営チームのサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為
          %li その他，運営チームが不適切と判断する行為
          %br
        %h2 第6条（本サービスの提供の停止等）
        %ol
          %li 運営チームは，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
          %ol
            %li 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合
            %li 地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合
            %li コンピュータまたは通信回線等が事故により停止した場合
            %li その他，運営チームが本サービスの提供が困難と判断した場合
          %li 運営チームは，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。
          %br
        %h2 第7条（利用制限および登録抹消）
        %ol
          %li 運営チームは，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。
          %ol
            %li 本規約のいずれかの条項に違反した場合
            %li 登録事項に虚偽の事実があることが判明した場合
            %li 料金等の支払債務の不履行があった場合
            %li 運営チームからの連絡に対し，一定期間返答がない場合
            %li 本サービスについて，最終の利用から一定期間利用がない場合
            %li その他，運営チームが本サービスの利用を適当でないと判断した場合
          %li 運営チームは，本条に基づき運営チームが行った行為によりユーザーに生じた損害について，一切の責任を負いません。
          %br
        %h2 第8条（退会）
        %p ユーザーは，運営チームの定める退会手続により，本サービスから退会できるものとします。
        %br
        %h2 第9条（保証の否認および免責事項）
        %ol
          %li 運営チームは，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。
          %li 運営チームは，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する運営チームとユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。
          %li 前項ただし書に定める場合であっても，運営チームは，運営チームの過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（運営チームまたはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，運営チームの過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。
          %li 運営チームは，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。
          %br
        %h2 第10条（サービス内容の変更等）
        %p 運営チームは，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。
        %br
        %h2 第11条（利用規約の変更）
        %p 運営チームは，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。
        %br
        %h2 第12条（個人情報の取扱い）
        %p 運営チームは，本サービスの利用によって取得する個人情報については，運営チーム「プライバシーポリシー」に従い適切に取り扱うものとします。
        %br
        %h2 第13条（通知または連絡）
        %p ユーザーと運営チームとの間の通知または連絡は，運営チームの定める方法によって行うものとします。運営チームは,ユーザーから,運営チームが別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。
        %br
        %h2 第14条（権利義務の譲渡の禁止）
        %p ユーザーは，運営チームの書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。
        %br
        %h2 第15条（準拠法・裁判管轄）
        %ol
          %li 本規約の解釈にあたっては，日本法を準拠法とします。
          %li 本サービスに関して紛争が生じた場合には，運営チームの本店所在地を管轄する裁判所を専属的合意管轄とします。
          %br
        %p 以上
  
  =render "footer"

app/views/tweets/search.html.haml
.wrapper
  = render "header"
  = render "main"
  = render "footer"

app/views/tweets/show.html.haml
.wrapper
  = render "header"
  -# .tweetshowhed
  -#   =current_user.name
  .tweetshow
    .tweetshow_shows
      .tweetshow_shows_user
        = link_to asset_url("/users/#{@tweet.user_id}") do
          =@tweet.user.name
        - if user_signed_in?&& current_user.id == @tweet.user_id
          .tweetshow_shows_user_edit
            %span
              %ul
                %li
                  = link_to edit_tweet_path do
                    %i.fas.fa-ellipsis-h
                %li
                  = link_to tweet_path, method: :delete do
                    %i.fas.fa-trash-alt
        - else
          .tweetshow_shows_user_edit
            %span
              %ul
                %li
                  -# = link_to edit_tweet_path do
                  %i.ooo.fas.fa-ellipsis-h
                %li
                  -# = link_to tweet_path, method: :delete do
                  %i.ooo.fas.fa-trash-alt

      .tweetImage
        = image_tag(@tweet.image_url)
      -# .kodeshousai ファッション説明
      .tweetText
        = simple_format @tweet.text
      .tweettweet 
      .tweetsex
        性別:
        = @tweet.sex
      .tweettalls
        身長:
        = @tweet.tall 
        cm
      .tweettemp
        目安気温:
        =@tweet.temp
        ℃  
      .tweettypestyle
        体質:
        =@tweet.typestyle
      .tweettext
        = @tweet.updated_at.strftime("%Y-%m-%d %H:%M")
      
       
        
      %br
        %h3.liketweet
          いいね: #{@tweet.likes.count}
          - if current_user.already_liked?(@tweet)
            = button_to  tweet_like_path(@tweet) , method: :delete do
              %i.favo.far.fa-heart
          - else
            = button_to tweet_likes_path(@tweet) do
              %i.favo.far.fa-heart
            
        -# %h2.liketweetuser いいねしたユーザー
        - @tweet.liked_users.each do |user|
          %li.tweetuserlikename= user.name 
        .ffsfas1 が「いいね！」しました
        .commentscoment
          %h4 
          - if @comments
            - @comments.each do |comment|
              %p
                %strong
                  = link_to comment.user.name, "/users/#{comment.user_id}"
                  ：
                = comment.text

                  
                  
        .commentsusers
          - if current_user
            .formcoment
            = form_with(model: [@tweet, @comment], local: true,id: "new_comment") do |form|
              = form.text_area :text, placeholder: "  コメントを追加...", rows: "2", class: "textbox"
              = form.submit "投稿する", class: "comments_sent"
  =render "footer"        

app/views/tweets/update.html.haml
.newreg
  .contents.row
    .success
      %h3.1ksk
        更新が完了しました。
      %a.btn{:href => "/tweets"} 投稿一覧へ戻る