config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"
  devise_for :users
  get 'tweets/index'
  
  # get 'about', to: 'static_pages#about'
  
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :users do
    member do
     get :following, :followers
    end
    collection do
      get 'about'
    end
    collection do
      get 'kiyaku'
    end
    collection do
      get 'privacy'
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
    collection do
      get 'search'
    end
    collection do
      get 'about'
    end
    collection do
      get 'kiyaku'
    end
    collection do
      get 'privacy'
    end
  end
    
  # get '/tweet/hashtag/:name', to: "tweets#hashtag"
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, presence: true #追記
  
         mount_uploader :image, ImageUploader

  
  # validates :profile, length: { maximum: 200 } #追記
  has_many :comments
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

  has_many :followings, through: :following_relationships
 
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
 
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  def self.search(search)
    if search
      User.where('name LIKE(?) or sex LIKE(?) ',  "%#{search}%","%#{search}%")
    else
      User.all
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected

  # サインアップ後のリダイレクト先をrootに変更
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all.order(created_at: :desc).page(params[:page]).per(20)
  end
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
    @tweets=@user.tweets
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
  end
  def search
    @user = User.search(params[:keyword]).order(created_at: :desc).page(params[:page]).per(20)
  end
  
  
  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
end

def followers
  @user  = User.find(params[:id])
  @users = @user.followers
  render 'show_follower'
end
  private
  def user_params
    params.require(:user).permit(:name,:image,:profile,:sex,:age,:tall).merge(user_id: current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
 end
end

app/views/users/_follow.html.haml
= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f|
  %div= f.hidden_field :following_id
  .gfffa
    = f.submit "フォロー", class: "btn btn-large btn-primary follow-btn"

app/views/users/_follow_form.html.haml
- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_footer.html.haml
.footer
  .footer_p
    %ul.footer_p_link
      %li.p-footer_link_list
        = link_to about_tweets_path do
          KStagramとは
      %li.p-footer_link_list
        = link_to kiyaku_tweets_path do
          利用規約
      %li.p-footer_link_list
        = link_to privacy_tweets_path do
          プライバシーポリシー
      %li.p-footer_link_list
        = link_to destroy_user_session_path, method: :delete do
          ログアウト
  .footersite Copyright © KStagram 2020

app/views/users/_header.html.haml
.header_bar
  %h1.header_1
  %a{ href: '/',class: 'header_main' }
    KStagram
  %ul.user_info
    %h3.search
      -# %form#form1{:action => "自分のサイトURL"}
      -#   %input#sbox{:name => "s", :placeholder => "検索", :type => "search"}/
      -#   %input#sbtn{:type => "submit", :value => "検索"}/
      = form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form|
        -# %li.fas.fa-search
        = form.text_field :keyword, placeholder: " 検索...", class: "search-input"
        %button.search-btn{:type => "submit"}
          %i.fas.fa-search
        
       
      

    %li.user_info_home
    = link_to root_path do
      %i.fas.fa-home
    %li.user_info_insta
    = link_to new_tweet_path do
      %i.fab.fa-instagram
    %li.user_info_heart
    = link_to root_path do
      %i.fas.fa-heart
    %li.user_info_insta
    = link_to asset_url("/users/#{current_user.id}") do
      %i.fa.fa-user
    

app/views/users/_shousai.html.haml
.aaaaaaa          
  %h3.llllls いいねしている投稿
  %table
    %tr.lsal
      %th.ssala ユーザ名
      %th.ssala タイトル
    - @users.liked_tweets.each do |tweet|
      %tr.kaaa
        %td.ssala
          %a{:href => "/users/#{tweet.user.id}"}= tweet.user.name
        %td.ssala
          %a{:href => "/tweets/#{tweet.id}"}= tweet.title

app/views/users/_stats.html.haml
- @user ||= current_user
.stats
  %a{:href => "#{following_user_path(@user)}"}
    %strong#following.stat
      .gggll  フォロー
      .gggggg
        = @user.followings.count
    
  %a{:href => "#{followers_user_path(@user)}"}
    %strong#followers.stat
      .ggglls フォロワー
      .gggggg
        = @user.followers.count
   

app/views/users/_unfollow.html.haml
= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f|
  = f.submit "フォロー中", class: "btn btn-large follow-btns"

app/views/users/index.html.haml
.wrapper
  = render "header"
  .gbl_main
    .gbl_main_title
      .gbl_main_title_container
        .gbl_main_title_container_titles
          %h1.tit.icon_font
            %span.ico
            %i.fab.fa-instagram
            %i.stst KStgramユーザー
            .kskskska
              = form_with(url: search_users_path, local: true, method: :get, class: "search-formss") do |form|
                = form.text_field :keyword, placeholder: "ユーザー検索", class: "search-inputss"
                %button.search-btnss{:type => "submit"}
                  %i.fa.fa-address-book
  .gbl_bodyssss
    .contentaasas
      -# %h1.useriinenameaa 登録ユーザー一覧
      %table
        %tr.kusowaro
          %th ユーザ名
          %th 性別
          %th 登録日
        - @users.each do |user|
          %tr.ssala
            %td 
              %a{:href => "/users/#{user.id}"}= user.name
            %td 
              =user.sex
            %td 
              = user.created_at.strftime("%Y-%m-%d %H:%M")
  = paginate(@users)
  =render "footer"
   

app/views/users/search.html.haml
.wrapper
  = render "header"
  .gbl_main
    .gbl_main_title
      .gbl_main_title_container
        .gbl_main_title_container_titles
          %h1.tit.icon_font
            %span.ico
            %i.fab.fa-instagram
            %i.stst KStgramユーザー
            .kskskska
              = form_with(url: search_users_path, local: true, method: :get, class: "search-formss") do |form|
                = form.text_field :keyword, placeholder: "ユーザー検索", class: "search-inputss"
                %button.search-btnss{:type => "submit"}
                  %i.fa.fa-address-book
  .gbl_bodyssss
    .contentaasas
      -# %h1.useriinenameaa 登録ユーザー一覧
      %table
        %tr.kusowaro
          %th ユーザ名
          %th 性別
          %th 登録日
        - @user.each do |user|
          %tr.ssala
            %td 
              %a{:href => "/users/#{user.id}"}= user.name
            %td 
              =user.sex
            %td 
              = user.created_at.strftime("%Y-%m-%d %H:%M")
  = paginate(@user)
  =render "footer"

app/views/users/show.html.haml
.wrapper
  = render "header"
  .gbl_main
    .gbl_main_title
      .gbl_main_title_container
        .gbl_main_title_container_titles
          %h1.tit.icon_font
            %span.ico
            %i.fab.fa-instagram
            %i.stst プロフィール画面
  .useriine
  .alsldlld
    .useriineiine
      .userprofs
        .userprofile 
          .user_sub
            .usersubimage
              %p.imageusers
                = image_tag(@user.image_url)
            .usersubproff
              - if current_user == @user
                %p.kskskaas
                  = link_to  edit_user_registration_path do
                    プロフィール編集
            = render 'follow_form'
            = render 'stats' 
            
          .user_mains
            .intro
              .ssssssa
                %h1.introuser
                =@user.name
              .metas
                %ul.metalist
                  %li.aaa
                  =@user.tall
                  cm
                  %li.bbb
                  =@user.sex
                  %li.ccc
                  =@user.age
                  歳
                  -# %li.ddd
                  -# =@user.froms
                  -# 出身
              %ul.metalistsss
                -# - if current_user == @user
                -#   = link_to  edit_user_registration_path do
                -#     プロフィール編集
                = link_to users_path do
                  %i.lslsls.fa.fa-users
              .metaprofile
                .missiisis
                %p.proffff
                  =@user.profile
                %br
  
  .aaaaaaa
    投稿一覧
    %h3.llllls 
    %table
      %tr.lsal
        %th.ssala タイトル
        %th.ssala 気温(℃)
        %th.ssala 日付
      - @tweets.each do |tweet|
        %tr.kaaa
          %td.ssala
            = link_to tweet.title, tweet_path(tweet.id), class: "content__right__top--title"
          %td.ssala
            = link_to tweet.temp
          %td.ssala
            = link_to tweet.updated_at.strftime("%Y-%m-%d %H:%M")
          
  
  .aaaaaaa          
    %h3.llllls いいねしている投稿
    %table
      %tr.lsal
        %th.ssala ユーザ名
        %th.ssala タイトル
      - @user.liked_tweets.each do |tweet|
        %tr.kaaa
          %td.ssala
            %a{:href => "/users/#{tweet.user.id}"}= tweet.user.name
          %td.ssala
            %a{:href => "/tweets/#{tweet.id}"}= tweet.title
  =render "footer"          
                    

app/views/users/show_follow.html.haml
.wrapper 
  =render "header"
  .gbl_main
    .gbl_main_title
      .gbl_main_title_container
        .gbl_main_title_container_titles
          %h1.tit.icon_font
            %span.ico
            %i.fab.fa-instagram
            %i.stst フォロー中
  .followmain
    - @user.followings.each do |user|
      %table
        %tr.ssssss
          %td= link_to user.name, user_path(user)
  = render 'footer'

app/views/users/show_follower.html.haml
.wrapper 
  =render "header"
  .gbl_main
    .gbl_main_title
      .gbl_main_title_container
        .gbl_main_title_container_titles
          %h1.tit.icon_font
            %span.ico
            %i.fab.fa-instagram
            %i.stst フォロワー
  .followmain
    - @user.followers.each do |user|
      %table
        %tr.ssssss
          %td= link_to user.name, user_path(user)
  =render "footer" 